logging:
  level:
    com.symphox.ecip.eds: DEBUG

spring:
  datasource:
    url: jdbc:mysql://ecip-db-cluster2.cluster-cb3ch9dhqppy.ap-northeast-1.rds.amazonaws.com:3306/ecip?useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2&serverTimezone=Asia/Taipei
    #    url: jdbc:mysql://172.30.137.63:3306/ecip?useLegacyDatetimeCode=false&serverTimezone=Asia/Taipei
    #    url: jdbc:mysql://${DB_HOSTNAME}:3306/ecip?useLegacyDatetimeCode=false&serverTimezone=Asia/Taipei
    #    url: jdbc:mysql://localhost:3306/ecip
    username: admin
    password: ecip#123%99$$
    #    username: root
    #    password: ecip123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1


